# SPRINT 5 - Combining Datasets (merge, join, concat)

In [11]:
import pandas as pd

In [ ]:
customers = pd.DataFrame({
    'customer_id': [1, 2, 3, 4],
    'customer': ['Anna', 'Marco', 'Luca', 'Giulia']
})

In [ ]:
purchases = pd.DataFrame({
    'customer_id': [1, 2, 5],
    'amount': [100, 50, 200]
})

In [12]:
pd.merge(customers,
         purchases,
         on='customer_id',
         how='inner')

   customer_id customer  amount
0            1     Anna     100
1            2    Marco      50

In [13]:
pd.concat([customers, purchases])

   customer_id customer  amount
0            1     Anna     NaN
1            2    Marco     NaN
2            3     Luca     NaN
3            4   Giulia     NaN
0            1      NaN   100.0
1            2      NaN    50.0
2            5      NaN   200.0